services:
  - type: web
    name: aidlink
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn AIDLINK.dynamic_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: DEBUG
        value: False
      - key: FLASK_ENV
        value: production


